[build-system]
requires = ["setuptools>=61.0", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "rpps"
version = "0.1.0"
description = "RF Parameter Processor Suite"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name = "Anonoei", email="to+dev@an0.cx"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",

    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["anonoei", "dsp", "sdr"]
dependencies = ["pyboiler-anonoei", "numpy", "matplotlib"]

[project.urls]
Homepage = "https://github.com/anonoei/RPPS"
Documentation = "https://anonoei.github.io/RPPS/"
Repository = "https://github.com/Anonoei/RPPS.git"
Issues = "https://github.com/Anonoei/RPPS/issues"
Source = "https://github.com/anonoei/RPPS"

[project.optional-dependencies]
dev = ["twine", "build", "bumpver", "pytest", "pdoc3"]

[tool.bumpver]
current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"'
]
"src/rpps/__init__.py" = ["{version}"]
